# Generated by Django 5.2.3 on 2026-04-23 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='products/')),
                ('view', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('side', 'Side')], max_length=10)),
                ('print_area_x', models.IntegerField()),
                ('print_area_y', models.IntegerField()),
                ('print_area_width', models.IntegerField()),
                ('print_area_height', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='customization.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_image', models.ImageField(upload_to='designs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RenderedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendered_file', models.ImageField(upload_to='rendered/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customization.productimage')),
                ('user_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customization.userdesign')),
            ],
        ),
    ]
