services:
  - type: web
    name: product-customization-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn product_customization.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
